### ISSUE TITLE
Create public site action plan

### ISSUE THREAD

**Issue by jaimiebutton** [bcgov/nr-rec-resources#12]
This ticket is to track the work needed to develop our plan for moving forward with replacing the RST public website, aligning with BC Parks website and the recreation strategy, and starting to build out backlog.

Anticipate this will carry on throughout Sprint 1.

**Acceptance Criteria:**
- [ ] connection with Osprey and CMS team to learn about current processes/tech stacks
  - [ ] note any outstanding questions and opportunities 
- [ ] work with Parks & Rec UX team on recommendations (this may not come until later in the sprint)

**Related:**
- related to #58

**Comment by FM-SM** [comment]
Duplicate #48 #58
