### ISSUE TITLE
Pull out content from CMS Lite for co-design worksop IA activity

### ISSUE THREAD

**Issue by jaimiebutton** [bcgov/nr-rec-resources#138]
Capturing this work in a ticket to be able to reference back in the future.

As part of our co-design session 1, we'll be doing some IA card sorting with staff to understand how information can be better structured for easy findability. To do this, we'll need to go through the current CMS lite structure and pull out content that can be sorted together with other sitesandtrailsbc.ca content. 

Acceptance Criteria:
 - [x] Export screens from CMS Lite
 - [x] Create site map from screenshots
 - [x] Mark up content that would be good candidates for a sorting activity
 - [x] Create list of sitckies that can be used for the co-design workshop 
 - [x] Document site map for future use

Links:
The CMS Lite site map/screenshots can be found in our "Information in FTA & CMS Lite" Mural board

**Comment by JLWade** [comment]
co-design stickies and current IA of cms site looks good - moving to done. 

I like the cartoons for the guidlines on cms
