### ISSUE TITLE
Design "find a rec site/trail" page

### ISSUE THREAD

**Issue by jaimiebutton** [bcgov/nr-rec-resources#144]
Wow, development's crushing it! Let's create another screen to be able to have another thing to start implementing. 

**Acceptance Criteria:**
- [x] Create a page with no search critera
- [x] Create a page with search results by city
- [x] Create a page with search results by rec site/trail name
- [x] Modify filters to match RST context
- [x] Pull out sample 'facilities' filter options from FTA
- [x] Pass to project team for feedback
- [x] Iterate on feedback as needed

**Notes**
- Designs can be found [in figma here](https://www.figma.com/design/TFDtavdpJE2vrB5vEmBB6w/RST---Basic-View?node-id=196-11594&t=nojXLfGmIdxZ0y5X-4)
- Marcel noticed a discrepancy in page width for BC Parks' 'find a park' page compared to other pages. The dev team decided to match the BC Parks width for this page for now and discuss with the wider design team in the new year.

**Comment by JLWade** [comment]
looks good! moving to done
