### ISSUE TITLE
Complete RST Dev Team onboarding checklist

### ISSUE THREAD

**Issue by JLWade** [bcgov/nr-rec-resources#21]
This tickets it to complete the basic RST dev team onboarding into program area and project background, communication channels, etc. This will provide some more context and familiarity with the project and future product development. 

#### Acceptance Criteria:
- [x] checklist has been completed: https://bcgov.sharepoint.com/:w:/r/teams/031072/Shared%20Documents/%5BProduct%5D%20RST%20Services/%5B3%5D%20General%20Admin/1%20-%20Onboarding/Onboarding%20List.docx?d=wd00d23a9896f42e8a0d957326e4bea24&csf=1&web=1&e=0krqBk
  - [x] @marcellmueller completed
  - [ ] alberto completed

#### Dependencies

- Access to Sharepoint for Alberto 

**Relevant documentation as reference**

**Definition of Ready**
TBD

**Definition of Done** 
TBD
#### Notes:
- 
-

**Comment by JLWade** [comment]
@albertoborit @marcellmueller @FM-SM  I think we can move this one to done ya?

**Comment by marcellmueller** [comment]
Yes I think we can move it to done!
