### ISSUE TITLE
Create team DoR

### ISSUE THREAD

**Issue by JLWade** [bcgov/nr-rec-resources#25]
#### Description:
This ticket is to come up with our teams Definition of Ready. This means a ticket/issue in the backlog is ready to be brought into the sprint.

#### Acceptance Criteria:

- [ ] DoR is added to our documentation
  - [ ] documented and dated in confluence
  - [ ] added to ticket templates  

#### Dependencies

- Blocked by #30 

**Relevant documentation as reference**

**Definition of Ready**
TBD

**Definition of Done** 
TBD

#### Notes:
- 
-

**Comment by FM-SM** [comment]
Moved into the #30 as a subtask (#74)

**Comment by BAAlexK** [comment]
Session held with team, first draft of definitions in mural. 

Starting on editing

**Comment by BAAlexK** [comment]
Complete - added to confluence https://apps.nrs.gov.bc.ca/int/confluence/display/BCPRS/Team+Members
