### ISSUE TITLE
Create team DoD

### ISSUE THREAD

**Issue by JLWade** [bcgov/nr-rec-resources#26]
#### Description:
This ticket is to come up with our teams Definition of Ready. This means a ticket/issue in the backlog is ready to be brought into the sprint.

#### Acceptance Criteria:

- [ ] DoR is added to our documentation  
  - [ ] documented in confluence
  - [ ] added to ticket templates where necessary

#### Dependencies

- Blocked by #30 

**Definition of Ready**
TBD

**Definition of Done** 
TBD

**Comment by FM-SM** [comment]
Archived - Moved it into the #30 as a subtask (#75)

**Comment by BAAlexK** [comment]
Session held with team, first draft of definitions in mural. 

Starting on editing

**Comment by BAAlexK** [comment]
Complete - added to confluence https://apps.nrs.gov.bc.ca/int/confluence/display/BCPRS/Team+Members
