### ISSUE TITLE
Create Team Agreements

### ISSUE THREAD

**Issue by JLWade** [bcgov/nr-rec-resources#30]
#### Description:
This ticket is for the team to create some team agreements for how to work together. There will be broader team agreements from inception with other teams but it would be good to have our own internal team agreements for how we want to work together as a dev team.

#### Acceptance Criteria:

- [x] Team agreements are created and documented somewhere

#### Dev Checklist
- [x] documented in confluence 

#### Dependencies

- Blocked by #27 - Done
- Relates to #25 
- Relates to #26 
- Relates to #29 

**Relevant documentation as reference**
- some broader large team agreements willl come out of the inception session - can use these as a basis and then create our own dev team agreements

**Definition of Ready**
TBD

**Definition of Done** 
TBD

#### Notes:
- 
-

**Comment by JLWade** [comment]
unblocking as inception is over

**Comment by BAAlexK** [comment]
Summarized team agreement discussion output, stylized and shared with team for review/comments.

**Comment by BAAlexK** [comment]
Team Agreement approved by team and published to Confluence https://apps.nrs.gov.bc.ca/int/confluence/display/BCPRS/Team+Members 

Marking ticket as done/closing
