### ISSUE TITLE
Decision: database

### ISSUE THREAD

**Issue by JLWade** [bcgov/nr-rec-resources#31]
What type of database do we want to use for storing the RST data?

This would include RST data currently within the FTA tool, potential new data items, and more. 

**Acceptance Criteria:**
- [x] meet with Forestry Digital Service team to hear how they have been doing this for other FTA uses
- [x] document rationale https://apps.nrs.gov.bc.ca/int/confluence/display/BCPRS/Tech+Stack+Rationale
- [x] generate a recommendation for database decision
  - [x] team and necessary collaborator agree on recommendation
- [x] Meet with Osprey team to understand their database as well
  
Notes:
Verify if there's any data need or API backwards compatibility with Forestry Digital Services need

https://bcgov.github.io/forestry-digital-services/

**Comment by FM-SM** [comment]
A meeting will be arranged with a technical team to help us on that

**Comment by JLWade** [comment]
decision made and rationale on confluence page - moving to done
