### ISSUE TITLE
Design basic view of rec site or trail

### ISSUE THREAD

**Issue by JLWade** [bcgov/nr-rec-resources#41]
#### Description:
 
This ticket is to come up with some very high level wireframes/designs to support future work on being able to view information about a rec site or trail on a webpage. 

This includes identifying **basic** info needed to be surfaced (that can be publicly shared - we will not address confidential info yet).

This prepares us for #24 and #28 in next sprint.
 
#### Acceptance Criteria:
- Wireframes to guide initial development and first iteration are saved in RST Figma space for reference
- Identify the basic public data that can be displayed on this page (not confidential)
 
 
**Definition of Ready**
 
- [x] Acceptance criteria are included
- [x] Dependencies are identified (technical, business, regulatory/policy)
- [x] Story has been estimated (under 13 pts)
 
**Definition of Done** 
 
- Code review:
- [x] High level design is peer reviewed 
  
- PO Review:
  - [ ] Reviewed and approved by Product Owner
 
#### Notes:
- 
-

**Comment by jaimiebutton** [comment]
Basic view can be found here: https://www.figma.com/design/TFDtavdpJE2vrB5vEmBB6w/RST---Basic-View?t=CWKu2ug3LioSIdrt-0
