### ISSUE TITLE
Identifying tech stack considerations & criteria for decisions

### ISSUE THREAD

**Issue by JLWade** [bcgov/nr-rec-resources#49]
This ticket is to come up with and investigate elements that we need to know before deciding on a tech stack.

Start of potential list:
- expected traffic
- expected database size
- external integrations
- stability
- telemetry & tracing
- log analysis
- alerts
- skillsets within this team
- skillsets on other PRDt teams
- linkages to other teams
- long term maintenance
 
AC:

- [x] determine list of criteria
- [x] figure out thresholds or levels that go with each criteria for FTA/RST module and RST public website
- [x] set up and have any meetings for further analysis or investigation

**Comment by marcellmueller** [comment]
@JLWade @albertoborit I started a very WIP word doc/brain dump file in our teams General channel. Feel free to add to this.

https://bcgov.sharepoint.com/:w:/r/teams/11160/Shared%20Documents/General/RST%20tech%20stack%20considerations.docx?d=w981cf157e09a421fb307c347f141a721&csf=1&web=1&e=qLCtQC

**Comment by FM-SM** [comment]
Blocked - Definition for the CMS

**Comment by JLWade** [comment]
Moving to done - additional work has been captured in other tickets.
