### ISSUE TITLE
Set up GitHub repos

### ISSUE THREAD

**Issue by marcellmueller** [bcgov/nr-rec-resources#51]
#### Description:

We need to set up our project GitHub repos so we can get started on development work. 

Some helpful links for setting up BC Government GitHub repos:
https://github.com/bcgov/BC-Policy-Framework-For-GitHub

Project lifecycle badges:
https://github.com/bcgov/repomountie/blob/master/doc/lifecycle-badges.md
 
#### Acceptance Criteria:
  
- [x] Ensure the team has access
- [x] Add basic README.md
- [x] Define whether or not multiple repos will be used (with names)
  - [x] Create those new repo(s)

**Comment by FM-SM** [comment]
more discussion will be needed to move forward with this ticket

**Comment by JLWade** [comment]
repo's readme's and decisions all made - moving to done
