### ISSUE TITLE
Set up Hosting Platform

### ISSUE THREAD

**Issue by JLWade** [bcgov/nr-rec-resources#59]
#### Description:
This ticket to set up hosting environment decided in #33 
 
#### Acceptance Criteria:

- [x] request environments through product registry
- [x] onboarding into environments for devs is set up and completed
- [x] devs can access environments

 
#### Dependencies
 
- Blocked by #33 

 
**Relevant documentation as reference**
 
 
**Definition of Ready**

 
**Definition of Done** 

 
#### Notes:
- 
-

**Comment by JLWade** [comment]
Moving out of blocked for me to set up AWS space :) 
FYI @marcellmueller

**Comment by JLWade** [comment]
Request sent through today! review is in progress

**Comment by JLWade** [comment]
@marcellmueller did you get any emails (to your gov one) about access to the new space? Should be up now and I have you and Om as admins.

e07de9

**Comment by marcellmueller** [comment]
No I haven't received anything yet!



Marcel Mueller (he/him)

Full Stack Developer | Button Inc.
Email: ***@***.*** | Phone: 778-966-4013

[cid:20aca65b-2445-47a1-a486-82ffbf81f810]

This e-mail and attachments are only for the use of the intended recipient and must not be distributed, disclosed, used, or copied by or to anyone else. If you receive this in error, please contact me immediately and delete all copies of this e-mail and any attachments.

________________________________
