### ISSUE TITLE
Deploy application into AWS

### ISSUE THREAD

**Issue by FM-SM** [bcgov/nr-rec-resources#63]
Deploy application into AWS

**Acceptance Criteria:**
- [x] Application gets deployed into AWS dev namespace via Terraform or Cloudformation
- [x] Frontend deployed on S3/Cloudfront
- [x] Postgres database deployed on Aurora RDS
- [x] NestJS API deployed on Fargate ECS
- [x] Frontend/Database/API communicate with each other and have accessible public route

### Bonus:
Depending on how smoothly this goes we may want to break this into another issue though it would be amazing if this was deployed via our GitHub actions pipeline.

**Comment by marcellmueller** [comment]
This is completed along with deployment pipeline to AWS via GitHub actions. 

Frontend: [https://dz37sfd9duckr.cloudfront.net/](https://dz37sfd9duckr.cloudfront.net/)
Swagger API docs: [https://qmxe1tmuig.execute-api.ca-central-1.amazonaws.com/api/docs](https://qmxe1tmuig.execute-api.ca-central-1.amazonaws.com/api/docs)

**Comment by JLWade** [comment]
app is up! moving this one to done.

@marcellmueller  can you add the swagger doc link to our readme? I couldnt find it so ignore if it's already there
