### ISSUE TITLE
Setup Frontends in AWS

### ISSUE THREAD

**Issue by JLWade** [bcgov/nr-rec-resources#92]
#### Description:
 
This ticket is to set up front end cloudfront components in AWS with React framework. Add bcparks gov bootstrap.

THIS TICKET NEEDS REFINEMENT
 
#### Acceptance Criteria:
[Note: Use 'Given/When/Then' format if it makes sense to. Otherwise, a simple checklist that can be tested.]
 
#### Development Checklist:
 
- [ ] ...
- [ ] ...
- [ ] ...
 
#### Dependencies
 
- Blocked by
- Blocking
 
**Relevant documentation as reference**

**Comment by marcellmueller** [comment]
Closing as we are combining this with #63
